### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by hartmark** [collector-bank/common-validation#8]
We're need to implement the new Finish national security number format and found this repo.

The repo has the changes implemented already but the nuget is not updated.

https://www.nuget.org/packages/Collector.Common.Validation.NationalIdentifier

Can you please bump the nuget release?

**Comment by vijuhe** [comment]
Any update on this? Would be good to get a new package so that we can keep on using the library.

**Comment by LinusNoren** [comment]
Hi, sorry for the delay. I just uploaded a new version to nuget.org

https://www.nuget.org/packages/Collector.Common.Validation.NationalIdentifier/
